// In-memory shoe catalog (sample data).
// Add more shoes by following the same schema.

window.SHOE_CATALOG = [
  // ROAD
  {
    id: "road-nimbus-26",
    brand: "ASICS",
    model: "Gel-Nimbus 26",
    category: "road",
    msrp: 160,
    weightG: 295,
    dropMm: 8,
    stackMm: 41,
    widthOptions: ["regular", "wide"],
    stability: "neutral", // neutral | mild | stability
    cushionFeel: "soft", // soft | balanced | firm
    ride: { cushioning: 9, responsiveness: 5, stability: 5, durability: 8, value: 7 },
    bestUse: ["easy", "daily"],
    distance: ["10k", "hm", "fm"],
    notes: ["Plush high-stack cruiser", "Comfort-focused upper", "Not the snappiest for speed work"],
  },
  {
    id: "road-1080v13",
    brand: "New Balance",
    model: "Fresh Foam X 1080 v13",
    category: "road",
    msrp: 165,
    weightG: 290,
    dropMm: 6,
    stackMm: 38,
    widthOptions: ["regular", "wide"],
    stability: "neutral",
    cushionFeel: "soft",
    ride: { cushioning: 9, responsiveness: 5, stability: 5, durability: 7, value: 6 },
    bestUse: ["easy", "daily"],
    distance: ["10k", "hm", "fm"],
    notes: ["Soft and protective", "Great for easy miles", "Can feel a bit mushy at fast paces"],
  },
  {
    id: "road-ghost-16",
    brand: "Brooks",
    model: "Ghost 16",
    category: "road",
    msrp: 140,
    weightG: 275,
    dropMm: 12,
    stackMm: 36,
    widthOptions: ["regular", "wide"],
    stability: "neutral",
    cushionFeel: "balanced",
    ride: { cushioning: 7, responsiveness: 6, stability: 6, durability: 8, value: 8 },
    bestUse: ["easy", "daily", "mixed"],
    distance: ["5k", "10k", "hm"],
    notes: ["Reliable daily trainer", "Good durability/value", "High drop may not suit everyone"],
  },
  {
    id: "road-gt-2000-12",
    brand: "ASICS",
    model: "GT-2000 12",
    category: "road",
    msrp: 140,
    weightG: 275,
    dropMm: 8,
    stackMm: 36,
    widthOptions: ["regular", "wide"],
    stability: "stability",
    cushionFeel: "balanced",
    ride: { cushioning: 7, responsiveness: 6, stability: 9, durability: 8, value: 8 },
    bestUse: ["easy", "daily"],
    distance: ["5k", "10k", "hm", "fm"],
    notes: ["Stable without feeling overly corrective", "Strong all-around pick for support seekers"],
  },
  {
    id: "road-hoka-clifton-9",
    brand: "HOKA",
    model: "Clifton 9",
    category: "road",
    msrp: 145,
    weightG: 248,
    dropMm: 5,
    stackMm: 36,
    widthOptions: ["regular", "wide"],
    stability: "neutral",
    cushionFeel: "soft",
    ride: { cushioning: 8, responsiveness: 5, stability: 5, durability: 7, value: 8 },
    bestUse: ["easy", "daily"],
    distance: ["10k", "hm", "fm"],
    notes: ["Light, soft daily mileage shoe", "Low drop", "Some runners want more snap"],
  },
  {
    id: "road-saucony-endorphin-speed-4",
    brand: "Saucony",
    model: "Endorphin Speed 4",
    category: "road",
    msrp: 170,
    weightG: 240,
    dropMm: 8,
    stackMm: 36,
    widthOptions: ["regular"],
    stability: "neutral",
    cushionFeel: "balanced",
    ride: { cushioning: 7, responsiveness: 9, stability: 6, durability: 7, value: 6 },
    bestUse: ["tempo", "mixed", "race"],
    distance: ["5k", "10k", "hm", "fm"],
    notes: ["Fast, versatile speed trainer", "Great for workouts and racing", "Regular width can run snug"],
  },
  {
    id: "road-nike-vaporfly-3",
    brand: "Nike",
    model: "Vaporfly 3",
    category: "road",
    msrp: 260,
    weightG: 198,
    dropMm: 8,
    stackMm: 40,
    widthOptions: ["regular"],
    stability: "neutral",
    cushionFeel: "balanced",
    ride: { cushioning: 7, responsiveness: 10, stability: 5, durability: 5, value: 3 },
    bestUse: ["race"],
    distance: ["10k", "hm", "fm"],
    notes: ["Top-tier race shoe for many runners", "Expensive and less durable"],
  },

  // TRAIL
  {
    id: "trail-salomon-speedcross-6",
    brand: "Salomon",
    model: "Speedcross 6",
    category: "trail",
    msrp: 140,
    weightG: 298,
    dropMm: 10,
    stackMm: 32,
    widthOptions: ["regular"],
    stability: "neutral",
    cushionFeel: "firm",
    ride: { cushioning: 5, responsiveness: 6, stability: 7, durability: 8, value: 8 },
    bestUse: ["mixed"],
    distance: ["5k", "10k", "hm"],
    trail: { lugMm: 5, grip: 9, protection: 6, rockPlate: false, terrain: ["muddy", "mixed"] },
    notes: ["Aggressive grip for soft ground", "Snug fit", "Firm ride on hardpack/road"],
  },
  {
    id: "trail-hoka-speedgoat-5",
    brand: "HOKA",
    model: "Speedgoat 5",
    category: "trail",
    msrp: 155,
    weightG: 291,
    dropMm: 4,
    stackMm: 33,
    widthOptions: ["regular", "wide"],
    stability: "neutral",
    cushionFeel: "soft",
    ride: { cushioning: 8, responsiveness: 6, stability: 6, durability: 7, value: 7 },
    bestUse: ["easy", "daily", "mixed"],
    distance: ["10k", "hm", "fm", "ultra"],
    trail: { lugMm: 5, grip: 8, protection: 8, rockPlate: false, terrain: ["rocky", "mixed", "buffed"] },
    notes: ["Protective, popular ultra shoe", "Great cushioning-to-grip balance"],
  },
  {
    id: "trail-brooks-cascadia-17",
    brand: "Brooks",
    model: "Cascadia 17",
    category: "trail",
    msrp: 140,
    weightG: 298,
    dropMm: 8,
    stackMm: 31,
    widthOptions: ["regular", "wide"],
    stability: "mild",
    cushionFeel: "balanced",
    ride: { cushioning: 6, responsiveness: 6, stability: 8, durability: 8, value: 8 },
    bestUse: ["daily", "mixed"],
    distance: ["10k", "hm", "fm"],
    trail: { lugMm: 4, grip: 7, protection: 8, rockPlate: true, terrain: ["rocky", "mixed"] },
    notes: ["Stable, protective trail workhorse", "Rock plate helps on sharp terrain"],
  },

  // TRACK
  {
    id: "track-nike-victory-2",
    brand: "Nike",
    model: "ZoomX Victory 2",
    category: "track",
    msrp: 190,
    weightG: 135,
    dropMm: 0,
    stackMm: 0,
    widthOptions: ["regular"],
    stability: "neutral",
    cushionFeel: "firm",
    ride: { cushioning: 3, responsiveness: 10, stability: 4, durability: 5, value: 5 },
    bestUse: ["race"],
    distance: ["5k", "10k"],
    track: { type: "spike", events: ["1500m", "3k", "5k", "10k"] },
    notes: ["Elite-level track spike", "Not for daily training"],
  },
  {
    id: "track-saucony-endorphin-md",
    brand: "Saucony",
    model: "Endorphin MD",
    category: "track",
    msrp: 130,
    weightG: 160,
    dropMm: 0,
    stackMm: 0,
    widthOptions: ["regular"],
    stability: "neutral",
    cushionFeel: "firm",
    ride: { cushioning: 3, responsiveness: 8, stability: 5, durability: 6, value: 7 },
    bestUse: ["race"],
    distance: ["5k", "10k"],
    track: { type: "spike", events: ["800m", "1500m", "3k"] },
    notes: ["Middle-distance focused spike", "More approachable price point"],
  },
];